### ISSUE TITLE
获取数据失败，无法正常加载

### ISSUE THREAD

**Issue by Coodool** [YuyingWu/hexo-tag-douban#1]
按照教程安装插件，并在文章中引入douban标签后保存，刷新浏览器后显示获取数据失败，无法正常加载豆瓣读书内容。

![image](https://user-images.githubusercontent.com/20887105/47786065-83e36580-dd45-11e8-815f-f69b5b5a4168.png)

**Comment by YuyingWu** [comment]
@Coodool 可以留下你调用的url，我看看能不能复现？

**Comment by Coodool** [comment]
@YuyingWu 我之前建站的时候遇到的上述情况，刚才重新尝试复现发现这个问题已经不存在了。但发现插件会和 fancyBox 这个库冲突：
- 无法点击图片跳转到豆瓣页面
- 样式上 img 标签的 `display: inline-block;` 样式会被 fancyBox 的 `display: block !important;` 覆盖。

**Comment by YuyingWu** [comment]
@Coodool 嗷~

1. 无法点击图片跳转到豆瓣页面。这种情况只能在插件的img上添加fancybox的“例外classname”去规避；
2. 在插件图片加上`!important`的样式，覆盖掉fancybox的样式。

你可能需要针对这个情况，起一个兼容fancybox的fork版本了，因为这些功能其实不属于插件本身的逻辑。如果你调试中途遇到的问题，还是可以过来提问哈，可以协助的话，我也会很乐意协助看看怎么解决你的问题 ：）
